version: "3.9"
services:
  mysql:
    image: mysql:5.7
    labels:
      lagoon.type: mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: pass
     MYSQL_DATABASE: drupal
     MYSQL_USER: drupal
     MYSQL_PASSWORD: drupal
